#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3308/testdb?useSSL=false
#    username: root
#    password: root
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 30000
##      idle-timeout: 600000
##      max-lifetime: 1800000
